/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {

    /**
     * Brute force approach.
     */
    public char findTheDifference1(String s, String t) {
        int[] table = new int[26];
        for (int i = 0; i < s.length(); i += 1) {
            char c = s.charAt(i);
            table[c - 'a'] += 1;
        }
        for (int i = 0; i < t.length(); i += 1) {
            char c = t.charAt(i);
            table[c - 'a'] -= 1;
            if (table[c - 'a'] < 0) return c;
        }
        return 'a';
    }

    /**
     * Bit manipulation with XOR. Same as problem: Single Number.
     * 2 pass
     */
    public char findTheDifference2(String s, String t) {
        char c = 0;
        for (int i = 0; i < s.length(); i += 1) {
            c ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i += 1) {
            c ^= t.charAt(i);
        }
        return c;
    }

    /**
     * 1 pass
     */
    public char findTheDifference3 (String s, String t) {
        char c = t.charAt(t.length() - 1);
        for (int i = 0; i < s.length(); i += 1) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }
    public static void main(String[] args) {
        String s = "ymbgaraibkfmvocpizdydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmoswrcxnargtlswqema" +
                "fandgkmydtimuzvjwxvlfwlhvkrgcsithaqlcvrihrwqkpjdhgfgreqo" +
                "xzfvhjzojhghfwbvpfzectwwhexthbsndovxejsntmjihchaotbgcysfdao" +
                "jkjldprwyrnischrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuink" +
                "yygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczcovrmwqxxbnhfzcjjcp" +
                "gzjjfateajnnvlbwhyppdleahgaypxidkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjs" +
                "zolgwqvfiozofncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrrymrf" +
                "dxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpqsspyssrmdhuelkk" +
                "vyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxkvwkrwdcxjfzikdyswsuxegm" +
                "htnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfo" +
                "vaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrc" +
                "wjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtel" +
                "hwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdj" +
                "kfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgdd" +
                "qwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor";
        System.out.println(s.indexOf("t"));

    }
}
